format = """
[](#83a598)\
$username\
[](bg:#8ec07c fg:#83a598)\
$directory\
[](fg:#8ec07c bg:#b16286)\
$git_branch\
$git_status\
[](fg:#b16286 bg:#d3859b)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#d3859b bg:#fe8019)\
$docker_context\
[](fg:#fe8019 bg:#a89984)\
$time\
[ ](fg:#a89984)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#83a598"
style_root = "bg:#83a598"
format = '[$user ]($style)'

[directory]
style = "bg:#8ec07c"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#d3859b"
format = '[[ $symbol ($version) ](bg:#d3859b)]($style)'

[docker_context]
symbol = " "
style = "bg:#fe8019"
format = '[[ $symbol $context ](bg:#fe8019)]($style) $path'

[elixir]
symbol = " "
style = "bg:#d3859b"
format = '[[ $symbol ($version) ](bg:#d3859b)]($style)'

[elm]
symbol = " "
style = "bg:#d3859b"
format = '[[ $symbol ($version) ](bg:#d3859b)]($style)'

[git_branch]
symbol = ""
style = "bg:#b16286"
format = '[[ $symbol $branch ](bg:#b16286)]($style)'

[git_status]
style = "bg:#b16286"
format = '[[($all_status$ahead_behind )](bg:#b16286)]($style)'

[golang]
symbol = " "
style = "bg:#d3859b"
format = '[[ $symbol ($version) ](bg:#d3859b)]($style)'

[haskell]
symbol = " "
style = "bg:#d3859b"
format = '[[ $symbol ($version) ](bg:#d3859b)]($style)'

[java]
symbol = " "
style = "bg:#d3859b"
format = '[[ $symbol ($version) ](bg:#d3859b)]($style)'

[julia]
symbol = " "
style = "bg:#d3859b"
format = '[[ $symbol ($version) ](bg:#d3859b)]($style)'

[nodejs]
symbol = ""
style = "bg:#d3859b"
format = '[[ $symbol ($version) ](bg:#d3859b)]($style)'

[nim]
symbol = " "
style = "bg:#d3859b"
format = '[[ $symbol ($version) ](bg:#d3859b)]($style)'

[rust]
symbol = ""
style = "bg:#d3859b"
format = '[[ $symbol ($version) ](bg:#d3859b)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#a89984"
format = '[[ ♥ $time ](bg:#a89984)]($style)'
