## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░
## CROSS-SHELL PROMPT
##
## rxyhn's starship configuration
## The minimal, blazing-fast, and infinitely customizable prompt for any shell!

format = "$all"
right_format = """$git_branch$git_status$cmd_duration$directory"""

# Disable the blank line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[character]
success_symbol = " [](green)"
error_symbol = " [](red)"
vicmd_symbol = "[  ](yellow)"

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[cmd_duration]
min_time = 1
format = "[](fg:black bg:none)[$duration]($style)[](fg:black bg:black)[](fg:purple bg:black)[](fg:black bg:purple)[](fg:purple bg:none) "
disabled = false
style = "fg:white bg:black"

[directory]
format = "[](fg:black bg:none)[$path]($style)[](fg:black bg:black)[](fg:blue bg:black)[](fg:black bg:blue)[](fg:blue bg:none)"
style = "fg:white bg:black"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[](fg:black bg:none)[$branch]($style)[](fg:black bg:black)[](fg:green bg:black)[](fg:black bg:green)[](fg:green bg:none) "
style = "fg:white bg:black"

[git_status]
format="[](fg:black bg:none)[$all_status$ahead_behind]($style)[](fg:black bg:black)[](fg:red bg:black)[](fg:black bg:red)[](fg:red bg:none) "
style = "fg:white bg:black"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '


