# Use custom format:
format="$directory$git_branch$character"

# Prompt symbols 
[character]
success_symbol = "[ \ue33e](#78dba9 bold)"
error_symbol = "[ ](#e05f65)"
vicmd_symbol = "[ ](#78dba9)"

[directory]
format = "[]($style)[[ ](bg:#384148 fg:#78dba9)$path](bg:#384148 fg:#dee1e6)[ ]($style)"
style = "bg:#101419 fg:#384148"

[git_branch]
format = "[]($style)[[ ](bg:#384148 fg:#fc7b81)$branch](bg:#384148 fg:#dee1e6)[]($style)"
style = "bg:#101419 fg:#384148"


