# Prompt from https://github.com/Syndrizzle/hotfiles

# Use custom format:
format="$directory$git_branch$character"

# Prompt symbols 
[character]
success_symbol = "[](green)"
error_symbol = "[](red)"
vicmd_symbol = "[](yellow)"

[directory]
format = "[]($style)[[ ](bg:bright-black fg:blue)$path](bg:bright-black fg:white)[ ]($style)"
style = "bg:black fg:bright-black"

[git_branch]
format = "[]($style)[[ ](bg:bright-black fg:red)$branch](bg:bright-black fg:white)[]($style)"
style = "fg:bright-black"
